pr:
  branches:
    include:
    - dev

variables:
    DotNetCoreVersion: '2.1.503'

jobs:
  - job: WindowsNetFramework
    pool:
      vmImage: 'VS2017-Win2016'

    steps:
    - task: CmdLine@1
      inputs:
        filename: C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools\sn.exe
        arguments: -Vr *,31bf3856ad364e35
    - task: MSBuild@1
      inputs:
        solution: build.proj
    - task: MSBuild@1
      inputs:
        solution: build.proj
        msbuildArguments: /t:RunTests /clp:ShowTimestamp /flp:Summary;Verbosity=minimal;LogFile=msbuild.sum /flp1:warningsonly;logfile=msbuild.wrn /flp2:errorsonly;logfile=msbuild.err /p:IgnorePathTokens="Microsoft.Rest.ClientRuntime.Tracing.Tests Microsoft.Azure.Services.AppAuthentication.IntegrationTests KeyVault\dataPlane LocationBasedServices Az.Auth.Tests BotService.Tests Search Batch.FileStaging.Tests Azure.Batch.IntegrationTests Azure.Batch.ProtocolTests Batch\Support\FileConventions AzureBatchFileConventions.IntegrationTests Batch\DataPlane\Azure.Batch.Unit.Tests Batch\DataPlane\Tools\ConfigureAwaitAnalyzer\ConfigureAwaitAnalyzer.Tests ContainerService\ContainerService.Tests PolicyInsights\Management\PolicyInsights.Tests Consumption\Consumption.Tests Billing\Billing.Tests ApplicationInsights\Management\ApplicationInsights.Tests Batch\Management\Management.Batch.Tests Storage\Storage.Tests Advisor\Advisor.Tests"
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunTitle: 'Test Results for PR# $(System.PullRequest.PullRequestNumber)'
        testResultsFiles: '**/*.trx'
        testResultsFormat: 'VSTest'
        mergeTestResults: false

  - job: LinuxNetStandard
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
        - task: DotNetCoreInstaller@0
          displayName: 'Use .NET Core sdk $(DotNetCoreVersion)'
          inputs:
            version: '$(DotNetCoreVersion)'
        - script: 'dotnet msbuild src/SDKs/Compute/Compute.sln'
          displayName: 'Build Net Core assets' 
